// ARTICLES
export const SET_ARTICLES = "SET_ARTICLES";
export const SET_CURRENT_ARTICLE = "SET_CURRENT_ARTICLE";
export const ADD_ARTICLE = "ADD_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";

// COMMENTS
export const SET_COMMENTS = "SET_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const SET_CURRENT_COMMENT = "SET_CURRENT_COMMENT";

export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
